name: Claude Code PR review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Load review prompt from file
        id: load-prompt
        run: |
          echo "PROMPT<<EOF" >> $GITHUB_ENV
          cat .claude/commands/custom-pr-review.md >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "REPO: ${{ github.repository }}" >> $GITHUB_ENV
          echo "PR NUMBER: ${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "上記のレビューポリシーに従って、このPRをレビューしてください。" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Debug prompt content
        run: |
          echo "===== PROMPT START ====="
          echo "${{ env.PROMPT }}"
          echo "===== PROMPT END ====="

      - name: PR Review with Progress Tracking
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: ${{ env.PROMPT }}
          track_progress: true
          claude_args: |
            --model claude-3-5-haiku-20241022
