name: PR Commenter

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  issues: write

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const repoName = context.repo.repo
            const prNumber = context.payload.pull_request.number
            const body = `@claude /custom-pr-review ${repoName} ${prNumber}`

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: repoName,
              issue_number: prNumber,
              body: body
            })
